[package]
name = "flagada"
version = "0.1.1"
entrypoint = "flags.typ"
authors = ["samrenault <renault.samuel@free.fr>"]
license = "MIT"
description = "A package to generate countries flags, selecting country based on its ISO3166-1 code"
repository = "https://github.com/samrenault/flagada"
keywords = ["display","flag","country flag"]
categories = ["visualization","components"]
exclude = ["doc/example_1.png","doc/example_2.png","doc/example_3.png","doc/example_4.png"]